name: Makefile CI

on: push

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install flex
        wget https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.gz
        tar -xf bison-3.8.2.tar.gz
        cd bison-3.8.2
        ./configure
        make
        sudo make install
    
    - name: Compile the lexer
      run : |
        make lexer

    - name: Run Lexer Tests with syntactically correct testcases
      run: |
        make lexer_correct_codes
    
    - name: Run Lexer Tests with syntactically incorrect testcases
      run: |
        make lexer_incorrect_codes

    - name: Compile the parser
      run : |
        make parser

    - name: Run Parser Tests with syntactically correct testcases
      run: |
        make parser_correct_codes

    - name: Run Parser Tests with syntactically incorrect testcases
      run: |
        make parser_incorrect_codes
