name: Makefile CI

on:
  push:
    branches: 
      - main
      - actions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
#     - name: configure
#       run: ./configure
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install flex
        sudo apt-get -y install bison
        cd src
        make all
      
    - name: Run tests on correct codes
      run: make test
      
    - name: Run tests on incorrect codes
      run: make error
