name: Makefile CI

on:
  push:
    branches: 
      - main
      - actions
      - Refactoring-and-Missing-features

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install flex
        sudo apt-get -y install bison
      
    - name: Run Lexer Tests with syntactically correct testcases
      run: |
        make lexer_correct_codes
    
    - name: Run Lexer Tests with syntactically incorrect testcases
      run: |
        make lexer_incorrect_codes

    - name: Run Parser Tests with syntactically correct testcases
      run: |
        make parser_correct_codes

    - name: Run Parser Tests with syntactically incorrect testcases
      run: |
        make parser_incorrect_codes
